#! /bin/sh

sxhkd &

# Compositor
compton & 

# Launch Polybar
$HOME/.config/polybar/launch.sh

# Desktop background
feh --bg-scale ~/Pictures/wallpaper.jpg

# Preserve my eyes 
redshift &

xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^4'
bspc rule -a Firefox desktop='^1'
bspc rule -a RuneScape desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
