#! /bin/sh

sxhkd &

# Compositor
compton & 

# Launch Polybar
$HOME/.config/polybar/launch.sh


# Set mouse ptr
xsetroot -cursor_name left_ptr

# Preserve my eyes 
$HOME/.redshift/launch.sh

WALLPAPER=~/.wallpaper/WatercolorFlora2_by_JulieSongInk1.jpg
# Desktop background
feh --bg-scale $WALLPAPER
wal -i $WALLPAPER -l 

# from https://github.com/dylanaraps/pywal/wiki/Customization#bspwm
# Source and set colours with wal
. "${HOME}/.cache/wal/colors.sh"

# Border colours
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15" 
bspc config presel_feedback_color "$color1"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^4'
bspc rule -a Firefox desktop='^1'
bspc rule -a RuneScape desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
